apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x7zp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-x7zp@sha256:b26b0e1b7734eaa31fc54e52c2ba65e653ad4c061aac9a20ed491bd4d0ceeafe
        name: my-nodejs
        resources: {}
status: {}
